[tool.poetry]
name = "ocr-pdf-extractor"
version = "0.1.0"
description = "A tool to extract text from scanned PDFs using OCR (Tesseract)."
authors = ["Nik Bamert"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.10"
pytesseract = "^0.3.10"
pdf2image = "^1.16.3"
Pillow = { version = "^9.5.0", extras = ["no-binary"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


